title: "Museum documentatie Naturalis"
baseURL: http://docs.museum.naturalis.nl
footnoteReturnLinkContents: â†©
languageCode: "en-us"
params:
  AuthorName: Naturalis Biodiversity Center
  SidebarRecentLimit: 5
  Subtitle: Documentatie t.b.v. ontwikkeling en beheer tentoonstellingen
  editURL: https://github.com/MakeExpose/naturalis-docs/edit/master/content/
  pluralizeListTitles: false
  disableInlineCopyToClipBoard: true
  themeVariant: naturalis
  enableGitInfo: true
  canonifyURLs: true
permalinks:
  post: /:year/:month/:title/
theme: "hugo-theme-learn"
outputs:
  home:
  - HTML
  - RSS
  - JSON
taxonomies:
  tentoonstelling: tentoonstellingen
  experience: experiences
  interactive: interactives
  exhibit: exhibits
  component: componenten
